apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-ebs-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests: 
      storage: 8Gi
